#
# Makefile for the totops drivers
#
obj-$(CONFIG_TOUCHSCREEN_FT5X0X)               	+= ft5x0x_ts.o
obj-$(CONFIG_TOTOPS_GSENEOR_MMA7660)           	+= mma7660.o
obj-$(CONFIG_TOTOPS_RFID)                      	+= totops_rfid.o
#obj-y                   			+= led.o
obj-$(CONFIG_SENSORS_MMA865X)			+= mma865x.o

